### ISSUE TITLE
Make User model/table

### ISSUE THREAD

**Issue by ditttu** [life-iitk/Lifeiitkbackend#1]

**Comment by tanvinerkar** [comment]
@bhuvansingla and I are switching from task #6 to this task. Suggestions?

**Comment by ditttu** [comment]
Let the columns of the table be: (roll, username, name, program, dept, hall, room, blood_group, gender, hometown, por, earlier_login, fblink)
Read [this](https://docs.djangoproject.com/en/2.2/topics/db/models/) to see how to make models.
Read [this](https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#jsonfield) to know about the json field used in por.
Try asking suggestions on slack after this.😅
