### ISSUE TITLE
Create an API end point to create events

### ISSUE THREAD

**Issue by ditttu** [life-iitk/Lifeiitkbackend#9]

**Comment by aaryans941** [comment]
@dryairship and I will be working on this.

**Comment by ditttu** [comment]
I suggest you guys first finish [this task ](https://github.com/ditttu/Lifeiitkbackend/issues/7)

**Comment by dryairship** [comment]
@aaryans941 Bola tha maine. :man_facepalming:

**Comment by aaryans941** [comment]
1. "Will be" hai , 2. that issue is closed now, jbtw

**Comment by ditttu** [comment]
You guys should start.
